
version: '3.3'

services:

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_development

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1

  postgres:
    image: postgres:11.1-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 9091:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 'hiagofss98@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'test@1234'

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root



  mongoclient:
    image: mongoclient/mongoclient
    container_name: mongo-client
    ports:
      - 8083:3000
    environment:
      STARTUP_DELAY: 10
      MONGO_URL: 'mongodb://root:root@mongo:27017/admin'

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025